import { NgModule } from '@angular/core';
import {
  MatToolbarModule,
  MatCardModule,
  MatProgressSpinnerModule,
  MatFormFieldModule,
  MatButtonModule,
  MatCheckboxModule,
  MatInputModule,
  MatTabsModule,
  MatMenuModule,
  MatDialogModule,
  MatProgressBarModule,
  MatRadioModule,
  MatSelectModule,
  MatIconModule,
  MatTableModule,
  MatSidenavModule,
  MatExpansionModule,
  MatSnackBarModule,
  MatPaginatorModule,
  MatBottomSheetModule
} from '@angular/material';

@NgModule({
  imports: [
    MatToolbarModule,
    MatCardModule,
    MatProgressSpinnerModule,
    MatFormFieldModule,
    MatButtonModule,
    MatCheckboxModule,
    MatInputModule,
    MatTabsModule,
    MatMenuModule,
    MatDialogModule,
    MatProgressBarModule,
    MatRadioModule,
    MatSelectModule,
    MatIconModule,
    MatTableModule,
    MatSidenavModule,
    MatExpansionModule,
    MatSnackBarModule,
    MatPaginatorModule,
    MatBottomSheetModule
  ],
  exports: [
    MatToolbarModule,
    MatCardModule,
    MatProgressSpinnerModule,
    MatFormFieldModule,
    MatButtonModule,
    MatCheckboxModule,
    MatInputModule,
    MatTabsModule,
    MatMenuModule,
    MatDialogModule,
    MatProgressBarModule,
    MatRadioModule,
    MatSelectModule,
    MatIconModule,
    MatTableModule,
    MatSidenavModule,
    MatExpansionModule,
    MatSnackBarModule,
    MatPaginatorModule,
    MatBottomSheetModule
  ]
})
export class MaterialModule {}
